### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by dlyon304** [zoombya/ox-serve#5]
After following install, connecting the the server locally gives me a blank page that says Upgrade Required

**Comment by m-matthies** [comment]
Hi Daniel, the way you connect to the server locally is using a web sockets connection from oxview's web page. 
So usually you are not exposed to any web page.

**Comment by dlyon304** [comment]
OK I see my mistake

**Comment by m-matthies** [comment]
Oh it's actually more interesting: 
https://stackoverflow.com/questions/35698061/why-node-js-requires-an-upgrade-while-trying-to-run-an-application-on-the-localh
So it's the header requiring an update from http to ws protocol.

**Comment by m-matthies** [comment]
Cool that you found it, was not aware of this "feature".

**Comment by dlyon304** [comment]
Haha yea in my mind it was hosting an oxview page with ox serve plugged in because the youtube tutorial showed a different page layout than the current ox view page, but it looks like it has just been updated since.

**Comment by m-matthies** [comment]
Yeah, if you would know the struggles I went through recording that other tutorial (: 
Need to update it thought at some point.

**Comment by dlyon304** [comment]
Well now I've got it down I can make a quick tutorial as a thanks.  Mail me at dlyon@wustl.edu if interested I've still got all the software needed from some past projects, so it should be pretty quick.
